const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");
let frames = 0;
let requestId;
let kids = [];
let monsters = [];
let candies = [];
let scoreText; 
let score = 0;
let playerLife = 3;
const numberOfKids = 25;
